### ISSUE TITLE
Fix Sidekiq 7.1 error handler deprecation

### ISSUE THREAD

**Issue by bdewater-thatch** [appsignal/appsignal-ruby#1001]
We noticed our Sidekiq job errors weren't reported to Appsignal anymore. On Sidekiq 7.1.5 with Appsignal 3.4.12 logs show:

```
2023-10-19T14:24:55.251Z pid=80636 tid=z18 WARN: RuntimeError: kaboom! test appsignal
2023-10-19T14:24:55.251Z pid=80636 tid=z18 WARN: app/jobs/blazer_checks_job.rb:8:in `perform'
2023-10-19T14:24:55.251Z pid=80636 tid=z18 ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2023-10-19T14:24:55.251Z pid=80636 tid=z18 ERROR: undefined method `arity' for #<Appsignal::Integrations::SidekiqErrorHandler:0x0000000105834f90>
2023-10-19T14:24:55.251Z pid=80636 tid=z18 ERROR: /Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:267:in `block in handle_exception'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `each'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `handle_exception'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
```
The issue was introduced in https://github.com/sidekiq/sidekiq/pull/6051 and fixed in 7.1.6 after this report: https://github.com/sidekiq/sidekiq/issues/6065

After bumping them gem locally, logs now show:
```
2023-10-19T14:33:29.024Z pid=81328 tid=4eg8 WARN: RuntimeError: kaboom! test appsignal
2023-10-19T14:33:29.025Z pid=81328 tid=4eg8 WARN: app/jobs/blazer_checks_job.rb:8:in `perform'
2023-10-19T14:33:29.025Z pid=81328 tid=4eg8 INFO: DEPRECATION: Sidekiq exception handlers now take three arguments, see #<Appsignal::Integrations::SidekiqErrorHandler:0x000000012a35c5c0>
```

**Comment by bdewater-thatch** [comment]
Fixed in https://github.com/appsignal/appsignal-ruby/commit/c8698dca465d84fdac33d88debc6fbb004458bf1
