### PR TITLE
Fix deprecation for Sidekiq 8.0 error handler changes

### LINKED ISSUE #1001: Fix Sidekiq 7.1 error handler deprecation
We noticed our Sidekiq job errors weren't reported to Appsignal anymore. On Sidekiq 7.1.5 with Appsignal 3.4.12 logs show:

```
2023-10-19T14:24:55.251Z pid=80636 tid=z18 WARN: RuntimeError: kaboom! test appsignal
2023-10-19T14:24:55.251Z pid=80636 tid=z18 WARN: app/jobs/blazer_checks_job.rb:8:in `perform'
2023-10-19T14:24:55.251Z pid=80636 tid=z18 ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2023-10-19T14:24:55.251Z pid=80636 tid=z18 ERROR: undefined method `arity' for #<Appsignal::Integrations::SidekiqErrorHandler:0x0000000105834f90>
2023-10-19T14:24:55.251Z pid=80636 tid=z18 ERROR: /Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:267:in `block in handle_exception'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `each'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `handle_exception'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
/Users/bdewater/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
```
The issue was introduced in https://github.com/sidekiq/sidekiq/pull/6051 and fixed in 7.1.6 after this report: https://github.com/sidekiq/sidekiq/issues/6065

After bumping them gem locally, logs now show:
```
2023-10-19T14:33:29.024Z pid=81328 tid=4eg8 WARN: RuntimeError: kaboom! test appsignal
2023-10-19T14:33:29.025Z pid=81328 tid=4eg8 WARN: app/jobs/blazer_checks_job.rb:8:in `perform'
2023-10-19T14:33:29.025Z pid=81328 tid=4eg8 INFO: DEPRECATION: Sidekiq exception handlers now take three arguments, see #<Appsignal::Integrations::SidekiqErrorHandler:0x000000012a35c5c0>
```

### PR DESCRIPTION
**Pull request by bdewater-thatch**
Sidekiq 7.1.5 introduces a change where the Sidekiq config is not passed in the context hash anymore, but as a separate positional argument. If the handler takes two arguments a deprecation warning is logged. In 8.0 this backwards compatibility will be dropped.

Since the config is not used at all, we can simply add an optional 3rd argument that works with old and new versions.

Fixes #1001 

## To do

- [x] Add changeset
- [x] Test on a Sidekiq version 7.1.6 / 8 app

### CODE REVIEW

**Comment by tombruijn** [comment]
Thanks for the fix @bdewater-thatch ! We'll test this in a Sidekiq 8 test app next week and merge it when we've seen it work.

**Comment by bdewater-thatch** [comment]
@tombruijn sounds good :) 

FWIW this is very similar to how Sidekiq itself tests the deprecation here: https://github.com/sidekiq/sidekiq/blob/7ba0792b2872b107c7820887812a9d3df727c153/test/exception_handler_test.rb#L39. There is no 8.0 version out yet where this will break loudly, so you'll probably want to check for the absence of the deprecation message currently logged.

**Comment by unflxw** [comment]
Thanks @bdewater-thatch! Works like a charm. Merged manually with an added changeset here: https://github.com/appsignal/appsignal-ruby/commit/c8698dca465d84fdac33d88debc6fbb004458bf1
